version: "3.3"
services:
  chocoapi:
    build: .
    image: chocoapi:latest
    expose:
      - ${APP_APPLICATION__PORT:-8000}
    ports:
      - "${APP_APPLICATION__PORT:-8000}:8000"
    env_file: .env
    # This waits for the redis and postgres images to be ready, but not for the databases to start.
    # For that we need to manually check in some way that postgres is ready to accept connections.
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health_check:${APP_APPLICATION__PORT:-8000}"]
      interval: 2s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    ports:
      # TODO: Unhardcode this
      - 6379:6379
    expose:
      - 6379

  # TODO: We might wanna use volumes here to be able to persist the db state to the local disk.
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    expose:
      - ${POSTGRES_PORT:-5432}
